"""LLM layer (Mukul, C1). The only place provider-specific code may live."""

from debugagent.llm.router import (
    LLMAuthError,
    LLMConfigError,
    LLMError,
    LLMRouter,
    LLMToolCallInvalid,
    LLMToolResourceLimit,
    LLMToolTurnLimit,
    LLMToolUnsupported,
    LLMUnavailable,
    Route,
    StructuredOutputError,
    StructuredResult,
    ToolLoopResult,
)
from debugagent.llm.tools import (
    MAX_CONVERSATION_CHARS,
    MAX_TOOL_ARGUMENT_CHARS,
    MAX_TOOL_CALLS_PER_TURN,
    MAX_TOOL_DEFINITION_CHARS,
    MAX_TOOL_RESULT_CHARS,
    MAX_TOOL_TURNS,
    TOOL_CHOICE_MODES,
    ToolCall,
    ToolCallError,
    ToolDefinition,
    ToolDefinitionError,
    ToolResourceLimit,
    ToolResultMessage,
)

__all__ = [
    "LLMAuthError",
    "LLMConfigError",
    "LLMError",
    "LLMRouter",
    "LLMToolCallInvalid",
    "LLMToolTurnLimit",
    "LLMToolUnsupported",
    "LLMUnavailable",
    "MAX_CONVERSATION_CHARS",
    "MAX_TOOL_ARGUMENT_CHARS",
    "MAX_TOOL_CALLS_PER_TURN",
    "MAX_TOOL_DEFINITION_CHARS",
    "MAX_TOOL_RESULT_CHARS",
    "MAX_TOOL_TURNS",
    "Route",
    "StructuredOutputError",
    "StructuredResult",
    "TOOL_CHOICE_MODES",
    "ToolCall",
    "ToolCallError",
    "ToolDefinition",
    "ToolDefinitionError",
    "ToolLoopResult",
    "ToolResourceLimit",
    "ToolResultMessage",
]
